export const LINKS_STATE_CHANGE = 'LINKS_STATE_CHANGE';

export const INIT_READY_CHANGE = 'INIT_READY_CHANGE';

export const COUNTRY_CHANGE = 'COUNTRY_CHANGE';

export const GET_TOP_NEWS_REQUESTED = 'GET_TOP_NEWS_REQUESTED';
export const GET_TOP_NEWS_DONE = 'GET_TOP_NEWS_DONE';

export const GET_CATEGORIES_REQUESTED = 'GET_CATEGORIES_REQUESTED';
export const GET_CATEGORIES_DONE = 'GET_CATEGORIES_DONE';

export const VIEW_NEWS_ITEM = 'VIEW_NEWS_ITEM';

export const INIT_READY_CHANGE_TN = 'INIT_READY_CHANGE_TN';
export const INIT_READY_CHANGE_CATEGORIES = 'INIT_READY_CHANGE_CATEGORIES';
export const INIT_READY_CHANGE_SEARCH = 'INIT_READY_CHANGE_SEARCH';

export const GET_DATA_ON_COUNTRY_CHANGE_REQUESTED =
  'GET_DATA_ON_COUNTRY_CHANGE_REQUESTED';
