export const LINKS_STATE_CHANGE = 'LINKS_STATE_CHANGE';

export const COUNTRY_CHANGE = 'COUNTRY_CHANGE';

export const GET_TOP_NEWS_REQUESTED = 'GET_TOP_NEWS_REQUESTED';
export const GET_TOP_NEWS_DONE = 'GET_TOP_NEWS_DONE';
